export const initialEmailTemplates = [
  {
    key: "newsletter_subscription_confirmation",
    name: "Newsletter subscription confirmation",
    subject: "Welcome to Nepal Heaven updates",
    html: '<h1>Welcome to Nepal Heaven</h1><p>Hi {{fullName}},</p><p>You are subscribed to considered Nepal travel inspiration, offers and trip updates.</p><p><a href="{{unsubscribeUrl}}">Unsubscribe from marketing emails</a></p>',
    text: "Hi {{fullName}},\n\nYou are subscribed to Nepal Heaven travel inspiration, offers and trip updates.\n\nUnsubscribe: {{unsubscribeUrl}}",
  },
  {
    key: "newsletter_admin_notification",
    name: "Newsletter admin notification",
    subject: "{{emailLeadEvent}} Email Lead — {{email}}",
    html: "<h1>{{emailLeadEvent}} Nepal Heaven Email Lead</h1><p><strong>Lead Type:</strong> Email Lead<br><strong>Source:</strong> {{subscriptionSource}}<br><strong>Email:</strong> {{email}}<br><strong>Subscribed At:</strong> {{subscribedAt}}<br><strong>Marketing Consent:</strong> Yes<br><strong>Lead Reference:</strong> {{reference}}</p>",
    text: "{{emailLeadEvent}} Nepal Heaven Email Lead\n\nLead Type: Email Lead\nSource: {{subscriptionSource}}\nEmail: {{email}}\nSubscribed At: {{subscribedAt}}\nMarketing Consent: Yes\nLead Reference: {{reference}}",
  },
  {
    key: "contact_customer_acknowledgment",
    name: "Contact customer acknowledgment",
    subject: "We've received your Nepal inquiry — Nepal Heaven",
    html: "<h1>We’ve received your Nepal inquiry</h1><p>Hi {{fullName}},</p><p>Thank you for reaching out to Nepal Heaven. We’ve safely received your inquiry.</p>{{summaryHtml}}<p>Our team will review your preferences and get back to you once we’ve identified the right journey or built the right plan for you.</p>",
    text: "Hi {{fullName}},\n\nThank you for reaching out to Nepal Heaven. We've safely received your inquiry.\n\n{{summaryText}}\n\nOur team will review your preferences and get back to you once we've identified the right journey or built the right plan for you.",
  },
  {
    key: "contact_admin_notification",
    name: "Contact admin notification",
    subject: "New Contact Inquiry — {{fullName}} — {{interestedIn}}",
    html: "<h1>New contact inquiry</h1>{{adminSummaryHtml}}",
    text: "New contact inquiry\n\n{{adminSummaryText}}",
  },
  {
    key: "destination_customer_acknowledgment",
    name: "Destination customer acknowledgment",
    subject: "You’re planning a journey to {{destinationName}}",
    html: "<h1>You’re planning a journey to {{destinationName}}</h1><p>Hi {{fullName}},</p><p>Thank you for reaching out to Nepal Heaven.</p><p>We can see you’re planning a journey to {{destinationName}} around {{preferredDate}}.</p><p>We’ve received your message and our team will review the destination, season, travel style and suitable journeys before getting back to you with the right direction for your trip.</p>",
    text: "Hi {{fullName}},\n\nThank you for reaching out to Nepal Heaven. We can see you're planning a journey to {{destinationName}} around {{preferredDate}}.\n\nWe've received your message and our team will review the destination, season, travel style and suitable journeys before getting back to you with the right direction for your trip.",
  },
  {
    key: "destination_admin_notification",
    name: "Destination admin notification",
    subject: "New Destination Inquiry — {{destinationName}} — {{fullName}}",
    html: "<h1>New destination inquiry</h1>{{adminSummaryHtml}}",
    text: "New destination inquiry\n\n{{adminSummaryText}}",
  },
  {
    key: "experience_customer_acknowledgment",
    name: "Experience customer acknowledgment",
    subject: "Your {{experienceName}} journey with Nepal Heaven",
    html: "<h1>Your {{experienceName}} journey</h1><p>Hi {{fullName}},</p><p>Thank you for reaching out to Nepal Heaven about {{experienceName}}.</p><p>We’ve received your preferences for around {{preferredDate}}. Our team will review the experience, season and suitable journeys before getting back to you. We won’t claim availability until it has been checked.</p>",
    text: "Hi {{fullName}},\n\nThank you for reaching out to Nepal Heaven about {{experienceName}}. We've received your preferences for around {{preferredDate}}. Our team will review the experience, season and suitable journeys before getting back to you. We won't claim availability until it has been checked.",
  },
  {
    key: "experience_admin_notification",
    name: "Experience admin notification",
    subject: "New Experience Inquiry — {{experienceName}} — {{fullName}}",
    html: "<h1>New experience inquiry</h1>{{adminSummaryHtml}}",
    text: "New experience inquiry\n\n{{adminSummaryText}}",
  },
  {
    key: "itinerary_customer_acknowledgment",
    name: "Itinerary customer acknowledgment",
    subject: "We’ve received your itinerary request — Nepal Heaven",
    html: "<h1>Your itinerary request is safely with us</h1><p>Hi {{fullName}},</p><p>Thank you for asking Nepal Heaven to shape your journey. We’ve received your request for {{destinationName}} around {{preferredDate}} and will review it before responding.</p>",
    text: "Hi {{fullName}},\n\nWe've received your itinerary request for {{destinationName}} around {{preferredDate}} and will review it before responding.",
  },
  {
    key: "itinerary_admin_notification",
    name: "Itinerary admin notification",
    subject: "New Itinerary Request — {{destinationName}} — {{fullName}}",
    html: "<h1>New itinerary request</h1>{{adminSummaryHtml}}",
    text: "New itinerary request\n\n{{adminSummaryText}}",
  },
  {
    key: "booking_customer_confirmation",
    name: "Booking customer confirmation",
    subject: "Booking Confirmed — {{bookingReference}} | Nepal Heaven",
    html: '<h1>Booking confirmed</h1><p>Hi {{customerName}},</p><p>{{paymentMessage}}</p><table role="presentation" width="100%" cellspacing="0" cellpadding="7"><tr><td><strong>Booking status</strong></td><td>{{bookingStatus}}</td></tr><tr><td><strong>Booking reference</strong></td><td>{{bookingReference}}</td></tr><tr><td><strong>Customer</strong></td><td>{{customerName}}</td></tr><tr><td><strong>Email</strong></td><td>{{customerEmail}}</td></tr><tr><td><strong>Phone</strong></td><td>{{customerPhone}}</td></tr><tr><td><strong>Journey</strong></td><td>{{packageName}}</td></tr><tr><td><strong>Destination</strong></td><td>{{destinationName}}</td></tr><tr><td><strong>Package tier</strong></td><td>{{tierName}}</td></tr><tr><td><strong>Start date</strong></td><td>{{startDate}}</td></tr><tr><td><strong>Travellers</strong></td><td>{{travellers}}</td></tr><tr><td><strong>Payment type</strong></td><td>{{paymentType}}</td></tr><tr><td><strong>Grand total</strong></td><td>{{currency}} {{grandTotal}}</td></tr><tr><td><strong>Amount paid</strong></td><td>{{currency}} {{amountPaid}}</td></tr><tr><td><strong>Remaining balance</strong></td><td>{{currency}} {{remainingBalance}}</td></tr><tr><td><strong>Payment status</strong></td><td>{{paymentStatus}}</td></tr><tr><td><strong>Payment method</strong></td><td>{{paymentMethod}}</td></tr><tr><td><strong>Payment reference</strong></td><td>{{paymentReference}}</td></tr></table><h2 style="margin-top:28px">Next steps</h2><p>Keep your booking reference safe. Our team will contact you regarding trip preparation. If any details need correction, reply to this email.</p><p><a href="{{bookingUrl}}" style="display:inline-block;background:#173d32;color:#ffffff;padding:12px 20px;border-radius:999px;text-decoration:none">View your booking</a></p>',
    text: "Booking confirmed\n\nHi {{customerName}},\n\n{{paymentMessage}}\n\nBooking Status: {{bookingStatus}}\nBooking Reference: {{bookingReference}}\nCustomer: {{customerName}}\nEmail: {{customerEmail}}\nPhone: {{customerPhone}}\nJourney: {{packageName}}\nDestination: {{destinationName}}\nPackage Tier: {{tierName}}\nStart Date: {{startDate}}\nTravellers: {{travellers}}\n\nPayment Type: {{paymentType}}\nGrand Total: {{currency}} {{grandTotal}}\nAmount Paid: {{currency}} {{amountPaid}}\nRemaining Balance: {{currency}} {{remainingBalance}}\nPayment Status: {{paymentStatus}}\nPayment Method: {{paymentMethod}}\nPayment Reference: {{paymentReference}}\n\nKeep your booking reference safe. Our team will contact you regarding trip preparation. View your booking: {{bookingUrl}}",
  },
  {
    key: "booking_admin_notification",
    name: "Booking admin notification",
    subject: "New Confirmed Booking — {{bookingReference}} — {{customerName}}",
    html: '<h1>New confirmed booking</h1><table role="presentation" width="100%" cellspacing="0" cellpadding="7"><tr><td><strong>Reference</strong></td><td>{{bookingReference}}</td></tr><tr><td><strong>Status</strong></td><td>{{bookingStatus}}</td></tr><tr><td><strong>Confirmed</strong></td><td>{{confirmedAt}}</td></tr><tr><td><strong>Customer</strong></td><td>{{customerName}}</td></tr><tr><td><strong>Email</strong></td><td>{{customerEmail}}</td></tr><tr><td><strong>Phone</strong></td><td>{{customerPhone}}</td></tr><tr><td><strong>Country / nationality</strong></td><td>{{customerCountry}}</td></tr><tr><td><strong>Package</strong></td><td>{{packageName}}</td></tr><tr><td><strong>Tier</strong></td><td>{{tierName}}</td></tr><tr><td><strong>Destination</strong></td><td>{{destinationName}}</td></tr><tr><td><strong>Start date</strong></td><td>{{startDate}}</td></tr><tr><td><strong>Travellers</strong></td><td>{{travellers}}</td></tr><tr><td><strong>Payment type</strong></td><td>{{paymentType}}</td></tr><tr><td><strong>Payment method</strong></td><td>{{paymentMethod}}</td></tr><tr><td><strong>Grand total</strong></td><td>{{currency}} {{grandTotal}}</td></tr><tr><td><strong>Amount paid</strong></td><td>{{currency}} {{amountPaid}}</td></tr><tr><td><strong>Remaining balance</strong></td><td>{{currency}} {{remainingBalance}}</td></tr><tr><td><strong>Payment status</strong></td><td>{{paymentStatus}}</td></tr><tr><td><strong>Payment reference</strong></td><td>{{paymentReference}}</td></tr></table><p><a href="{{bookingUrl}}">Open admin booking record</a></p>',
    text: "New confirmed booking\n\nReference: {{bookingReference}}\nStatus: {{bookingStatus}}\nConfirmed: {{confirmedAt}}\n\nCustomer\nName: {{customerName}}\nEmail: {{customerEmail}}\nPhone: {{customerPhone}}\nCountry / nationality: {{customerCountry}}\n\nPackage\nPackage: {{packageName}}\nTier: {{tierName}}\nDestination: {{destinationName}}\nStart Date: {{startDate}}\nTravellers: {{travellers}}\n\nPayment\nPayment Type: {{paymentType}}\nPayment Method: {{paymentMethod}}\nGrand Total: {{currency}} {{grandTotal}}\nAmount Paid: {{currency}} {{amountPaid}}\nRemaining Balance: {{currency}} {{remainingBalance}}\nPayment Status: {{paymentStatus}}\nPayment Reference: {{paymentReference}}\n\nBooking record: {{bookingUrl}}",
  },
  {
    key: "booking_cancellation_customer",
    name: "Booking cancellation customer",
    subject: "Booking Cancelled — {{bookingReference}} | Nepal Heaven",
    html: '<h1>Booking cancelled</h1><p>Hi {{customerName}},</p><p>Your booking has been cancelled.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="7"><tr><td><strong>Booking status</strong></td><td>Cancelled</td></tr><tr><td><strong>Booking reference</strong></td><td>{{bookingReference}}</td></tr><tr><td><strong>Journey</strong></td><td>{{packageName}}</td></tr><tr><td><strong>Tier</strong></td><td>{{tierName}}</td></tr><tr><td><strong>Destination</strong></td><td>{{destinationName}}</td></tr><tr><td><strong>Travel date</strong></td><td>{{startDate}}</td></tr><tr><td><strong>Travellers</strong></td><td>{{travellers}}</td></tr><tr><td><strong>Cancellation date</strong></td><td>{{cancelledAt}}</td></tr><tr><td><strong>Cancellation reason</strong></td><td>{{cancellationReason}}</td></tr><tr><td><strong>Grand total</strong></td><td>{{currency}} {{grandTotal}}</td></tr><tr><td><strong>Amount paid</strong></td><td>{{currency}} {{amountPaid}}</td></tr><tr><td><strong>Cancellation fee</strong></td><td>{{currency}} {{cancellationFeeAmount}}</td></tr><tr><td><strong>Refund due</strong></td><td>{{currency}} {{refundDue}}</td></tr><tr><td><strong>Refund status</strong></td><td>{{refundStatus}}</td></tr><tr><td><strong>Refund processing deadline</strong></td><td>{{refundDeadline}}</td></tr></table><p>{{refundMessage}}</p><p><a href="{{customerBookingUrl}}" style="display:inline-block;background:#173d32;color:#ffffff;padding:12px 20px;border-radius:999px;text-decoration:none">View your booking</a></p>',
    text: "Booking cancelled\n\nHi {{customerName}},\n\nBooking Status: Cancelled\nBooking Reference: {{bookingReference}}\nJourney: {{packageName}}\nTier: {{tierName}}\nDestination: {{destinationName}}\nTravel Date: {{startDate}}\nTravellers: {{travellers}}\nCancellation Date: {{cancelledAt}}\nCancellation Reason: {{cancellationReason}}\n\nGrand Total: {{currency}} {{grandTotal}}\nAmount Paid: {{currency}} {{amountPaid}}\nCancellation Fee: {{currency}} {{cancellationFeeAmount}}\nRefund Due: {{currency}} {{refundDue}}\nRefund Status: {{refundStatus}}\nRefund Processing Deadline: {{refundDeadline}}\n\n{{refundMessage}}\n\nView your booking: {{customerBookingUrl}}",
  },
  {
    key: "booking_cancellation_admin",
    name: "Booking cancellation admin",
    subject: "Booking Cancelled — {{bookingReference}} — {{customerName}}",
    html: '<h1>Booking cancelled</h1><table role="presentation" width="100%" cellspacing="0" cellpadding="7"><tr><td><strong>Reference</strong></td><td>{{bookingReference}}</td></tr><tr><td><strong>Status</strong></td><td>Cancelled</td></tr><tr><td><strong>Cancelled</strong></td><td>{{cancelledAt}}</td></tr><tr><td><strong>Reason</strong></td><td>{{cancellationReason}}</td></tr><tr><td><strong>Customer</strong></td><td>{{customerName}}</td></tr><tr><td><strong>Email</strong></td><td>{{customerEmail}}</td></tr><tr><td><strong>Phone</strong></td><td>{{customerPhone}}</td></tr><tr><td><strong>Country / nationality</strong></td><td>{{customerCountry}}</td></tr><tr><td><strong>Package</strong></td><td>{{packageName}}</td></tr><tr><td><strong>Tier</strong></td><td>{{tierName}}</td></tr><tr><td><strong>Destination</strong></td><td>{{destinationName}}</td></tr><tr><td><strong>Travel date</strong></td><td>{{startDate}}</td></tr><tr><td><strong>Travellers</strong></td><td>{{travellers}}</td></tr><tr><td><strong>Grand total</strong></td><td>{{currency}} {{grandTotal}}</td></tr><tr><td><strong>Total paid</strong></td><td>{{currency}} {{amountPaid}}</td></tr><tr><td><strong>Previously refunded</strong></td><td>{{currency}} {{previouslyRefunded}}</td></tr><tr><td><strong>Cancellation fee type</strong></td><td>{{cancellationFeeType}}</td></tr><tr><td><strong>Policy value</strong></td><td>{{cancellationFeeValue}}</td></tr><tr><td><strong>Cancellation fee charged</strong></td><td>{{currency}} {{cancellationFeeAmount}}</td></tr><tr><td><strong>Refund due</strong></td><td>{{currency}} {{refundDue}}</td></tr><tr><td><strong>Refund status</strong></td><td>{{refundStatus}}</td></tr><tr><td><strong>Refund deadline</strong></td><td>{{refundDeadline}}</td></tr><tr><td><strong>Payment reference(s)</strong></td><td>{{paymentReference}}</td></tr></table><p><a href="{{adminCancelledBookingUrl}}">Open cancelled booking record</a></p>',
    text: "Booking cancelled\n\nReference: {{bookingReference}}\nStatus: Cancelled\nCancelled: {{cancelledAt}}\nReason: {{cancellationReason}}\n\nCustomer\nName: {{customerName}}\nEmail: {{customerEmail}}\nPhone: {{customerPhone}}\nCountry / nationality: {{customerCountry}}\n\nJourney\nPackage: {{packageName}}\nTier: {{tierName}}\nDestination: {{destinationName}}\nTravel Date: {{startDate}}\nTravellers: {{travellers}}\n\nPayment / Refund\nGrand Total: {{currency}} {{grandTotal}}\nTotal Paid: {{currency}} {{amountPaid}}\nPreviously Refunded: {{currency}} {{previouslyRefunded}}\nCancellation Fee Type: {{cancellationFeeType}}\nPolicy Value: {{cancellationFeeValue}}\nCancellation Fee Charged: {{currency}} {{cancellationFeeAmount}}\nRefund Due: {{currency}} {{refundDue}}\nRefund Status: {{refundStatus}}\nRefund Deadline: {{refundDeadline}}\nPayment Reference(s): {{paymentReference}}\n\nCancelled booking record: {{adminCancelledBookingUrl}}",
  },
  {
    key: "customer_email_verification",
    name: "Customer email verification",
    subject: "Welcome to Nepal Heaven — Verify Your Email",
    html: '<h1>Welcome aboard, {{customerName}}</h1><p>Before your Nepal Heaven account is activated, please verify your email.</p><p style="font-size:30px;font-weight:bold;letter-spacing:8px;text-align:center">{{verificationCode}}</p><p style="text-align:center"><a href="{{verificationUrl}}" style="display:inline-block;background:#173d32;color:#fff;padding:12px 20px;border-radius:999px;text-decoration:none">Verify Email</a></p><p>The link opens your verification page; you must enter the six-digit code to activate the account. The code expires in {{expiryMinutes}} minutes.</p>',
    text: "Welcome aboard, {{customerName}}.\n\nVerification code: {{verificationCode}}\n\nOpen the verification page: {{verificationUrl}}\n\nThe link alone does not activate your account. Enter the code within {{expiryMinutes}} minutes.",
  },
  {
    key: "customer_email_verified",
    name: "Customer email verified",
    subject: "Your Nepal Heaven Email Is Verified",
    html: '<h1>Your email is verified</h1><p>Hi {{customerName}},</p><p>Your email has been successfully verified and your Nepal Heaven account is ready.</p><p>You are already signed in and can now explore destinations, packages and experiences, manage bookings and plan your Nepal journey.</p><p><a href="{{accountUrl}}" style="display:inline-block;background:#173d32;color:#fff;padding:12px 20px;border-radius:999px;text-decoration:none">Explore Nepal Heaven</a></p>',
    text: "Hi {{customerName}},\n\nYour email has been successfully verified and your Nepal Heaven account is ready. You are already signed in.\n\nExplore your account: {{accountUrl}}",
  },
  {
    key: "admin_new_traveller_registered",
    name: "Admin new traveller registered",
    subject: "New Traveller Registered — {{customerName}}",
    html: '<h1>New traveller registered</h1><p><strong>Registration Status:</strong> Email Verified</p><table role="presentation" width="100%" cellspacing="0" cellpadding="7"><tr><td><strong>Name</strong></td><td>{{customerName}}</td></tr><tr><td><strong>Email</strong></td><td>{{customerEmail}}</td></tr><tr><td><strong>Phone</strong></td><td>{{customerPhone}}</td></tr><tr><td><strong>Country</strong></td><td>{{customerCountry}}</td></tr><tr><td><strong>Nationality</strong></td><td>{{customerNationality}}</td></tr><tr><td><strong>Date of birth</strong></td><td>{{customerDateOfBirth}}</td></tr><tr><td><strong>Customer reference</strong></td><td>{{customerReference}}</td></tr><tr><td><strong>Verified</strong></td><td>{{verifiedAt}}</td></tr></table>',
    text: "New traveller registered\n\nRegistration Status: Email Verified\nName: {{customerName}}\nEmail: {{customerEmail}}\nPhone: {{customerPhone}}\nCountry: {{customerCountry}}\nNationality: {{customerNationality}}\nDate of Birth: {{customerDateOfBirth}}\nCustomer Reference: {{customerReference}}\nVerified: {{verifiedAt}}",
  },
  {
    key: "customer_password_reset",
    name: "Customer password reset",
    subject: "Reset Your Nepal Heaven Password",
    html: '<h1>Reset your password</h1><p>Hi {{customerName}},</p><p>Use the secure one-time link below to choose a new password. It expires in {{expiryMinutes}} minutes.</p><p><a href="{{resetUrl}}" style="display:inline-block;background:#173d32;color:#fff;padding:12px 20px;border-radius:999px;text-decoration:none">Reset Password</a></p><p>If you did not request this, you can ignore this email.</p>',
    text: "Hi {{customerName}},\n\nReset your password using this one-time link (expires in {{expiryMinutes}} minutes):\n{{resetUrl}}\n\nIf you did not request this, ignore this email.",
  },
  {
    key: "admin_password_reset",
    name: "Admin password reset",
    subject: "Reset Your Nepal Heaven Admin Password",
    html: '<h1>Reset administrator password</h1><p>Hi {{customerName}},</p><p>Use the secure one-time link below to reset your Nepal Heaven administrator password. It expires in {{expiryMinutes}} minutes.</p><p><a href="{{resetUrl}}" style="display:inline-block;background:#173d32;color:#fff;padding:12px 20px;border-radius:999px;text-decoration:none">Reset Admin Password</a></p><p>If you did not request this, contact the platform owner and ignore this email.</p>',
    text: "Hi {{customerName}},\n\nReset your Nepal Heaven administrator password using this one-time link (expires in {{expiryMinutes}} minutes):\n{{resetUrl}}\n\nIf you did not request this, ignore this email.",
  },
] as const;
