import { useState } from "react";
import { createFileRoute, Link, redirect, useNavigate, useRouter } from "@tanstack/react-router";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { AdminShell } from "@/components/admin/AdminShell";
import { CrmPagination } from "@/components/admin/CrmPagination";
import { getAdminSessionFn } from "@/lib/auth.functions";
import { countryName, countryOptions } from "@/lib/countries";
import { bookingCrmQuerySchema } from "@/lib/finance-crm.schema";
import { deleteVatRuleFn, getCrmBookingsFn, getFinancialRulesFn, saveVatRuleFn, updateFinancialDefaultsFn } from "@/lib/finance-crm.functions";

export const Route=createFileRoute("/admin_/crm/bookings")({validateSearch:(s)=>bookingCrmQuerySchema.parse(s),loaderDeps:({search})=>search,loader:async({deps})=>{if(!(await getAdminSessionFn()))throw redirect({to:"/admin",search:{redirect:"/admin/crm/bookings"}});const [bookings,rules]=await Promise.all([getCrmBookingsFn({data:deps}),getFinancialRulesFn()]);return{bookings,rules};},component:BookingsPage});
const money=(v:number,c:string)=>new Intl.NumberFormat("en-US",{style:"currency",currency:c}).format(v);
const date=(v:string|null)=>v?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:"Asia/Kathmandu"}).format(new Date(v)):"—";

function BookingsPage(){const {bookings,rules}=Route.useLoaderData(),search=Route.useSearch(),navigate=useNavigate({from:Route.fullPath}),router=useRouter();const [defaults,setDefaults]=useState({defaultVat:String(rules.defaultVat),cancellationFee:String(rules.cancellationFee)});const [editing,setEditing]=useState<null|{id:string|null;name:string;percentage:string;countries:string[]}>(null);const [deleting,setDeleting]=useState<string|null>(null);const [error,setError]=useState("");
const setSearch=(patch:Partial<typeof search>)=>void navigate({search:{...search,...patch},replace:true});
async function saveDefaults(){setError("");try{await updateFinancialDefaultsFn({data:{defaultVat:Number(defaults.defaultVat),cancellationFee:Number(defaults.cancellationFee)}});await router.invalidate();}catch{setError("Financial defaults could not be saved.");}}
async function saveRule(){if(!editing)return;const result=await saveVatRuleFn({data:{id:editing.id,name:editing.name,percentage:Number(editing.percentage),countries:editing.countries}});if(!result.ok){setError(result.message);return;}setEditing(null);await router.invalidate();}
return <AdminShell><main className="min-w-0 max-w-full p-5 sm:p-7 lg:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">CRM · Financial records</p><h1 className="mt-2 text-4xl font-semibold text-[#0c1724]">Bookings</h1><div className="mt-6 flex flex-wrap gap-2">{(["confirmed","cancelled"] as const).map(tab=><button key={tab} onClick={()=>setSearch({tab,page:1})} className={`rounded-full px-5 py-2.5 text-sm font-bold capitalize ${search.tab===tab?"bg-[#0c1724] text-white":"border bg-white"}`}>{tab} Bookings</button>)}</div><div className="mt-5 rounded-2xl border bg-white p-4"><input value={search.q} onChange={e=>setSearch({q:e.target.value,page:1})} placeholder="Search reference, customer, email or package" className="w-full rounded-xl border px-4 py-3" /></div>
<section className="mt-5 max-w-full overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="border-b bg-black/[.02] text-xs uppercase text-muted-foreground"><tr>{["SN","Reference","Customer","Package / Trip","Travel Date","Travellers","Booking Date","Subtotal","VAT","Total","Payment","Status","Actions"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{bookings.rows.map((b,i)=><tr key={b.id} className="border-b last:border-0"><td className="px-4 py-4">{(bookings.page-1)*bookings.pageSize+i+1}</td><td className="px-4 font-mono text-xs font-bold">{b.reference}</td><td className="px-4"><b>{b.customerName}</b><br/><span className="text-xs text-muted-foreground">{b.customerEmail}</span></td><td className="px-4">{b.packageName}</td><td className="px-4">{date(b.travelDate)}</td><td className="px-4">{b.travellers}</td><td className="px-4">{date(b.createdAt)}</td><td className="px-4">{money(b.subtotal,b.currency)}</td><td className="px-4">{b.vatPercentage===null?"Unknown":`${b.vatPercentage}% (${money(b.vatAmount,b.currency)})`}</td><td className="px-4 font-bold">{money(b.total,b.currency)}</td><td className="px-4">{b.paymentStatus}</td><td className="px-4 capitalize">{b.status}</td><td className="px-4"><Link to="/admin/crm/bookings/$reference" params={{reference:b.reference}} className="font-bold text-gold">View Booking</Link></td></tr>)}</tbody></table>{!bookings.rows.length?<p className="p-10 text-center text-muted-foreground">No matching {search.tab} bookings.</p>:null}<CrmPagination page={bookings.page} totalPages={bookings.totalPages} total={bookings.total} label="bookings" onPage={page=>setSearch({page})}/></section>
<section className="mt-10"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-semibold">Financial Rules</h2><p className="text-sm text-muted-foreground">Current rules apply only to future calculations. Booking snapshots remain unchanged.</p></div><button onClick={()=>setEditing({id:null,name:"",percentage:"",countries:[]})} className="inline-flex items-center gap-2 rounded-full bg-[#0c1724] px-5 py-3 text-sm font-bold text-white"><Plus className="h-4 w-4"/> Add Country VAT Rule</button></div>{error?<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}<div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">Default VAT</h3><input type="number" min="0" max="100" step=".01" value={defaults.defaultVat} onChange={e=>setDefaults({...defaults,defaultVat:e.target.value})} className="mt-3 w-full rounded-xl border px-4 py-3"/><h3 className="mt-5 font-semibold">Cancellation Fee</h3><input type="number" min="0" max="100" step=".01" value={defaults.cancellationFee} onChange={e=>setDefaults({...defaults,cancellationFee:e.target.value})} className="mt-3 w-full rounded-xl border px-4 py-3"/><button onClick={()=>void saveDefaults()} className="mt-5 rounded-full bg-[#0c1724] px-5 py-2.5 text-sm font-bold text-white">Save Rules</button></div><div className="space-y-3">{rules.rules.map(rule=><div key={rule.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{rule.name} · {rule.percentage}%</h3><p className="mt-2 text-sm text-muted-foreground">{rule.countries.map(c=>countryName(c)||c).join(", ")}</p></div><div className="flex gap-2"><button onClick={()=>setEditing({id:rule.id,name:rule.name,percentage:String(rule.percentage),countries:rule.countries})}><Pencil className="h-4 w-4"/></button><button onClick={()=>setDeleting(rule.id)} className="text-red-600"><Trash2 className="h-4 w-4"/></button></div></div></div>)}</div></div></section></main>
{editing?<div className="fixed inset-0 z-50 grid place-items-center bg-black/55 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6"><h2 className="text-2xl font-semibold">{editing.id?"Edit":"Add"} VAT Rule</h2><input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="Rule name" className="mt-5 w-full rounded-xl border px-4 py-3"/><input type="number" value={editing.percentage} onChange={e=>setEditing({...editing,percentage:e.target.value})} placeholder="VAT percentage" className="mt-3 w-full rounded-xl border px-4 py-3"/><div className="mt-4 grid max-h-64 gap-2 overflow-y-auto rounded-xl border p-3 sm:grid-cols-2">{countryOptions().map(c=><label key={c.value} className="flex gap-2 text-sm"><input type="checkbox" checked={editing.countries.includes(c.value)} onChange={()=>setEditing({...editing,countries:editing.countries.includes(c.value)?editing.countries.filter(x=>x!==c.value):[...editing.countries,c.value]})}/>{c.label}</label>)}</div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setEditing(null)} className="rounded-full border px-5 py-2">Cancel</button><button onClick={()=>void saveRule()} className="rounded-full bg-[#0c1724] px-5 py-2 font-bold text-white">Save Rule</button></div></div></div>:null}
{deleting?<div className="fixed inset-0 z-50 grid place-items-center bg-black/55 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6"><h2 className="text-2xl font-semibold">Delete VAT rule?</h2><p className="mt-3 text-sm text-muted-foreground">Existing bookings retain their original VAT percentage and amount.</p><div className="mt-6 flex justify-end gap-2"><button onClick={()=>setDeleting(null)} className="rounded-full border px-5 py-2">Cancel</button><button onClick={async()=>{await deleteVatRuleFn({data:{id:deleting}});setDeleting(null);await router.invalidate()}} className="rounded-full bg-red-700 px-5 py-2 font-bold text-white">Delete Rule</button></div></div></div>:null}</AdminShell>}
