/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as AdminCmsRouteImport } from './routes/admin_.cms'
import { Route as AdminCrmRouteImport } from './routes/admin_.crm'
import { Route as AdminDashboardRouteImport } from './routes/admin_.dashboard'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin_.forgot-password'
import { Route as AdminReportsRouteImport } from './routes/admin_.reports'
import { Route as AdminResetPasswordRouteImport } from './routes/admin_.reset-password'
import { Route as AdminSettingsRouteImport } from './routes/admin_.settings'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as BookingPaymentRouteImport } from './routes/booking.payment'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as AccountBookingsReferenceRouteImport } from './routes/account_.bookings.$reference'
import { Route as AdminCmsEmailTemplatesRouteImport } from './routes/admin_.cms_.email-templates'
import { Route as AdminCmsGeneralRouteImport } from './routes/admin_.cms_.general'
import { Route as AdminCmsEmailTemplatesKeyRouteImport } from './routes/admin_.cms_.email-templates_.$key'
import { Route as AdminCrmBookingsCancelledReferenceRouteImport } from './routes/admin_.crm.bookings.cancelled.$reference'
import { Route as AdminCrmBookingsConfirmedReferenceRouteImport } from './routes/admin_.crm.bookings.confirmed.$reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/admin_/cms',
  path: '/admin/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/admin_/crm',
  path: '/admin/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin_/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin_/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin_/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin_/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin_/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPaymentRoute = BookingPaymentRouteImport.update({
  id: '/booking/payment',
  path: '/booking/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExperiencesRoute,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/packages/$slug',
  path: '/packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsReferenceRoute =
  AccountBookingsReferenceRouteImport.update({
    id: '/account_/bookings/$reference',
    path: '/account/bookings/$reference',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCmsEmailTemplatesRoute = AdminCmsEmailTemplatesRouteImport.update({
  id: '/admin_/cms_/email-templates',
  path: '/admin/cms/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsGeneralRoute = AdminCmsGeneralRouteImport.update({
  id: '/admin_/cms_/general',
  path: '/admin/cms/general',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsEmailTemplatesKeyRoute =
  AdminCmsEmailTemplatesKeyRouteImport.update({
    id: '/admin_/cms_/email-templates_/$key',
    path: '/admin/cms/email-templates/$key',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCrmBookingsCancelledReferenceRoute =
  AdminCrmBookingsCancelledReferenceRouteImport.update({
    id: '/bookings/cancelled/$reference',
    path: '/bookings/cancelled/$reference',
    getParentRoute: () => AdminCrmRoute,
  } as any)
const AdminCrmBookingsConfirmedReferenceRoute =
  AdminCrmBookingsConfirmedReferenceRouteImport.update({
    id: '/bookings/confirmed/$reference',
    path: '/bookings/confirmed/$reference',
    getParentRoute: () => AdminCrmRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/payment': typeof BookingPaymentRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/account/bookings/$reference': typeof AccountBookingsReferenceRoute
  '/admin/cms/email-templates': typeof AdminCmsEmailTemplatesRoute
  '/admin/cms/general': typeof AdminCmsGeneralRoute
  '/admin/cms/email-templates/$key': typeof AdminCmsEmailTemplatesKeyRoute
  '/admin/crm/bookings/cancelled/$reference': typeof AdminCrmBookingsCancelledReferenceRoute
  '/admin/crm/bookings/confirmed/$reference': typeof AdminCrmBookingsConfirmedReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/payment': typeof BookingPaymentRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/account/bookings/$reference': typeof AccountBookingsReferenceRoute
  '/admin/cms/email-templates': typeof AdminCmsEmailTemplatesRoute
  '/admin/cms/general': typeof AdminCmsGeneralRoute
  '/admin/cms/email-templates/$key': typeof AdminCmsEmailTemplatesKeyRoute
  '/admin/crm/bookings/cancelled/$reference': typeof AdminCrmBookingsCancelledReferenceRoute
  '/admin/crm/bookings/confirmed/$reference': typeof AdminCrmBookingsConfirmedReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin_/cms': typeof AdminCmsRoute
  '/admin_/crm': typeof AdminCrmRouteWithChildren
  '/admin_/dashboard': typeof AdminDashboardRoute
  '/admin_/forgot-password': typeof AdminForgotPasswordRoute
  '/admin_/reports': typeof AdminReportsRoute
  '/admin_/reset-password': typeof AdminResetPasswordRoute
  '/admin_/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/payment': typeof BookingPaymentRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/account_/bookings/$reference': typeof AccountBookingsReferenceRoute
  '/admin_/cms_/email-templates': typeof AdminCmsEmailTemplatesRoute
  '/admin_/cms_/general': typeof AdminCmsGeneralRoute
  '/admin_/cms_/email-templates_/$key': typeof AdminCmsEmailTemplatesKeyRoute
  '/admin_/crm/bookings/cancelled/$reference': typeof AdminCrmBookingsCancelledReferenceRoute
  '/admin_/crm/bookings/confirmed/$reference': typeof AdminCrmBookingsConfirmedReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/compare'
    | '/contact'
    | '/experiences'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/registration'
    | '/reset-password'
    | '/search'
    | '/unsubscribe'
    | '/verify-email'
    | '/whatsapp'
    | '/admin/cms'
    | '/admin/crm'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/blog/$slug'
    | '/book/$slug'
    | '/booking/payment'
    | '/booking/success'
    | '/destinations/$slug'
    | '/experiences/$slug'
    | '/packages/$slug'
    | '/blog/'
    | '/destinations/'
    | '/packages/'
    | '/account/bookings/$reference'
    | '/admin/cms/email-templates'
    | '/admin/cms/general'
    | '/admin/cms/email-templates/$key'
    | '/admin/crm/bookings/cancelled/$reference'
    | '/admin/crm/bookings/confirmed/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/compare'
    | '/contact'
    | '/experiences'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/registration'
    | '/reset-password'
    | '/search'
    | '/unsubscribe'
    | '/verify-email'
    | '/whatsapp'
    | '/admin/cms'
    | '/admin/crm'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/blog/$slug'
    | '/book/$slug'
    | '/booking/payment'
    | '/booking/success'
    | '/destinations/$slug'
    | '/experiences/$slug'
    | '/packages/$slug'
    | '/blog'
    | '/destinations'
    | '/packages'
    | '/account/bookings/$reference'
    | '/admin/cms/email-templates'
    | '/admin/cms/general'
    | '/admin/cms/email-templates/$key'
    | '/admin/crm/bookings/cancelled/$reference'
    | '/admin/crm/bookings/confirmed/$reference'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/compare'
    | '/contact'
    | '/experiences'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/registration'
    | '/reset-password'
    | '/search'
    | '/unsubscribe'
    | '/verify-email'
    | '/whatsapp'
    | '/admin_/cms'
    | '/admin_/crm'
    | '/admin_/dashboard'
    | '/admin_/forgot-password'
    | '/admin_/reports'
    | '/admin_/reset-password'
    | '/admin_/settings'
    | '/blog/$slug'
    | '/book/$slug'
    | '/booking/payment'
    | '/booking/success'
    | '/destinations/$slug'
    | '/experiences/$slug'
    | '/packages/$slug'
    | '/blog/'
    | '/destinations/'
    | '/packages/'
    | '/account_/bookings/$reference'
    | '/admin_/cms_/email-templates'
    | '/admin_/cms_/general'
    | '/admin_/cms_/email-templates_/$key'
    | '/admin_/crm/bookings/cancelled/$reference'
    | '/admin_/crm/bookings/confirmed/$reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  ExperiencesRoute: typeof ExperiencesRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  RegistrationRoute: typeof RegistrationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WhatsappRoute: typeof WhatsappRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCrmRoute: typeof AdminCrmRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BookSlugRoute: typeof BookSlugRoute
  BookingPaymentRoute: typeof BookingPaymentRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  PackagesSlugRoute: typeof PackagesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  AccountBookingsReferenceRoute: typeof AccountBookingsReferenceRoute
  AdminCmsEmailTemplatesRoute: typeof AdminCmsEmailTemplatesRoute
  AdminCmsGeneralRoute: typeof AdminCmsGeneralRoute
  AdminCmsEmailTemplatesKeyRoute: typeof AdminCmsEmailTemplatesKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms': {
      id: '/admin_/cms'
      path: '/admin/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/crm': {
      id: '/admin_/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/dashboard': {
      id: '/admin_/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/forgot-password': {
      id: '/admin_/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reports': {
      id: '/admin_/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reset-password': {
      id: '/admin_/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/settings': {
      id: '/admin_/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/payment': {
      id: '/booking/payment'
      path: '/booking/payment'
      fullPath: '/booking/payment'
      preLoaderRoute: typeof BookingPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/packages/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/bookings/$reference': {
      id: '/account_/bookings/$reference'
      path: '/account/bookings/$reference'
      fullPath: '/account/bookings/$reference'
      preLoaderRoute: typeof AccountBookingsReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/email-templates': {
      id: '/admin_/cms_/email-templates'
      path: '/admin/cms/email-templates'
      fullPath: '/admin/cms/email-templates'
      preLoaderRoute: typeof AdminCmsEmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/general': {
      id: '/admin_/cms_/general'
      path: '/admin/cms/general'
      fullPath: '/admin/cms/general'
      preLoaderRoute: typeof AdminCmsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/email-templates_/$key': {
      id: '/admin_/cms_/email-templates_/$key'
      path: '/admin/cms/email-templates/$key'
      fullPath: '/admin/cms/email-templates/$key'
      preLoaderRoute: typeof AdminCmsEmailTemplatesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/crm/bookings/cancelled/$reference': {
      id: '/admin_/crm/bookings/cancelled/$reference'
      path: '/bookings/cancelled/$reference'
      fullPath: '/admin/crm/bookings/cancelled/$reference'
      preLoaderRoute: typeof AdminCrmBookingsCancelledReferenceRouteImport
      parentRoute: typeof AdminCrmRoute
    }
    '/admin_/crm/bookings/confirmed/$reference': {
      id: '/admin_/crm/bookings/confirmed/$reference'
      path: '/bookings/confirmed/$reference'
      fullPath: '/admin/crm/bookings/confirmed/$reference'
      preLoaderRoute: typeof AdminCrmBookingsConfirmedReferenceRouteImport
      parentRoute: typeof AdminCrmRoute
    }
  }
}

interface ExperiencesRouteChildren {
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
}

const ExperiencesRouteChildren: ExperiencesRouteChildren = {
  ExperiencesSlugRoute: ExperiencesSlugRoute,
}

const ExperiencesRouteWithChildren = ExperiencesRoute._addFileChildren(
  ExperiencesRouteChildren,
)

interface AdminCrmRouteChildren {
  AdminCrmBookingsCancelledReferenceRoute: typeof AdminCrmBookingsCancelledReferenceRoute
  AdminCrmBookingsConfirmedReferenceRoute: typeof AdminCrmBookingsConfirmedReferenceRoute
}

const AdminCrmRouteChildren: AdminCrmRouteChildren = {
  AdminCrmBookingsCancelledReferenceRoute:
    AdminCrmBookingsCancelledReferenceRoute,
  AdminCrmBookingsConfirmedReferenceRoute:
    AdminCrmBookingsConfirmedReferenceRoute,
}

const AdminCrmRouteWithChildren = AdminCrmRoute._addFileChildren(
  AdminCrmRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  ExperiencesRoute: ExperiencesRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  RegistrationRoute: RegistrationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WhatsappRoute: WhatsappRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCrmRoute: AdminCrmRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BookSlugRoute: BookSlugRoute,
  BookingPaymentRoute: BookingPaymentRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  PackagesSlugRoute: PackagesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  AccountBookingsReferenceRoute: AccountBookingsReferenceRoute,
  AdminCmsEmailTemplatesRoute: AdminCmsEmailTemplatesRoute,
  AdminCmsGeneralRoute: AdminCmsGeneralRoute,
  AdminCmsEmailTemplatesKeyRoute: AdminCmsEmailTemplatesKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
