/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as AdminCmsRouteImport } from './routes/admin_.cms'
import { Route as AdminCrmRouteImport } from './routes/admin_.crm'
import { Route as AdminDashboardRouteImport } from './routes/admin_.dashboard'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin_.forgot-password'
import { Route as AdminReportsRouteImport } from './routes/admin_.reports'
import { Route as AdminResetPasswordRouteImport } from './routes/admin_.reset-password'
import { Route as AdminSettingsRouteImport } from './routes/admin_.settings'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as BookingPaymentRouteImport } from './routes/booking.payment'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as ExperiencesSlugRouteImport } from './routes/experiences.$slug'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as AccountBookingsReferenceRouteImport } from './routes/account_.bookings.$reference'
import { Route as AdminCmsAboutRouteImport } from './routes/admin_.cms_.about'
import { Route as AdminCmsAuthenticationRouteImport } from './routes/admin_.cms_.authentication'
import { Route as AdminCmsBlogRouteImport } from './routes/admin_.cms_.blog'
import { Route as AdminCmsBookingRouteImport } from './routes/admin_.cms_.booking'
import { Route as AdminCmsContactRouteImport } from './routes/admin_.cms_.contact'
import { Route as AdminCmsDestinationsRouteImport } from './routes/admin_.cms_.destinations'
import { Route as AdminCmsEmailTemplatesRouteImport } from './routes/admin_.cms_.email-templates'
import { Route as AdminCmsExperiencesRouteImport } from './routes/admin_.cms_.experiences'
import { Route as AdminCmsFooterRouteImport } from './routes/admin_.cms_.footer'
import { Route as AdminCmsFormsRouteImport } from './routes/admin_.cms_.forms'
import { Route as AdminCmsGalleryRouteImport } from './routes/admin_.cms_.gallery'
import { Route as AdminCmsGeneralRouteImport } from './routes/admin_.cms_.general'
import { Route as AdminCmsHomeRouteImport } from './routes/admin_.cms_.home'
import { Route as AdminCmsMediaRouteImport } from './routes/admin_.cms_.media'
import { Route as AdminCmsNavigationRouteImport } from './routes/admin_.cms_.navigation'
import { Route as AdminCmsOtherSettingsRouteImport } from './routes/admin_.cms_.other-settings'
import { Route as AdminCmsPackagesRouteImport } from './routes/admin_.cms_.packages'
import { Route as AdminCmsSeoRouteImport } from './routes/admin_.cms_.seo'
import { Route as AdminCmsTestimonialsRouteImport } from './routes/admin_.cms_.testimonials'
import { Route as AdminCrmBookingsRouteImport } from './routes/admin_.crm.bookings'
import { Route as AdminCrmCustomersRouteImport } from './routes/admin_.crm.customers'
import { Route as AdminCrmLeadsRouteImport } from './routes/admin_.crm.leads'
import { Route as AdminCrmPaymentsRouteImport } from './routes/admin_.crm.payments'
import { Route as AdminCmsBlogIdRouteImport } from './routes/admin_.cms_.blog_.$id'
import { Route as AdminCmsBlogListingPageRouteImport } from './routes/admin_.cms_.blog_.listing-page'
import { Route as AdminCmsBlogNewRouteImport } from './routes/admin_.cms_.blog_.new'
import { Route as AdminCmsDestinationsIdRouteImport } from './routes/admin_.cms_.destinations_.$id'
import { Route as AdminCmsDestinationsListingPageRouteImport } from './routes/admin_.cms_.destinations_.listing-page'
import { Route as AdminCmsDestinationsNewRouteImport } from './routes/admin_.cms_.destinations_.new'
import { Route as AdminCmsEmailTemplatesKeyRouteImport } from './routes/admin_.cms_.email-templates_.$key'
import { Route as AdminCmsExperiencesIdRouteImport } from './routes/admin_.cms_.experiences_.$id'
import { Route as AdminCmsExperiencesListingPageRouteImport } from './routes/admin_.cms_.experiences_.listing-page'
import { Route as AdminCmsExperiencesNewRouteImport } from './routes/admin_.cms_.experiences_.new'
import { Route as AdminCmsMediaIdRouteImport } from './routes/admin_.cms_.media_.$id'
import { Route as AdminCmsNavigationKeyRouteImport } from './routes/admin_.cms_.navigation_.$key'
import { Route as AdminCmsPackagesIdRouteImport } from './routes/admin_.cms_.packages_.$id'
import { Route as AdminCmsPackagesListingPageRouteImport } from './routes/admin_.cms_.packages_.listing-page'
import { Route as AdminCmsPackagesNewRouteImport } from './routes/admin_.cms_.packages_.new'
import { Route as AdminCmsTestimonialsIdRouteImport } from './routes/admin_.cms_.testimonials_.$id'
import { Route as AdminCmsTestimonialsNewRouteImport } from './routes/admin_.cms_.testimonials_.new'
import { Route as AdminCrmBookingsReferenceRouteImport } from './routes/admin_.crm.bookings_.$reference'
import { Route as AdminCrmCustomersIdRouteImport } from './routes/admin_.crm.customers_.$id'
import { Route as AdminCrmBookingsCancelledReferenceRouteImport } from './routes/admin_.crm.bookings_.cancelled.$reference'
import { Route as AdminCrmBookingsConfirmedReferenceRouteImport } from './routes/admin_.crm.bookings_.confirmed.$reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/admin_/cms',
  path: '/admin/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/admin_/crm',
  path: '/admin/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin_/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin_/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin_/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin_/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin_/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPaymentRoute = BookingPaymentRouteImport.update({
  id: '/booking/payment',
  path: '/booking/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesSlugRoute = ExperiencesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExperiencesRoute,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/packages/$slug',
  path: '/packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBookingsReferenceRoute =
  AccountBookingsReferenceRouteImport.update({
    id: '/account_/bookings/$reference',
    path: '/account/bookings/$reference',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCmsAboutRoute = AdminCmsAboutRouteImport.update({
  id: '/admin_/cms_/about',
  path: '/admin/cms/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsAuthenticationRoute = AdminCmsAuthenticationRouteImport.update({
  id: '/admin_/cms_/authentication',
  path: '/admin/cms/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsBlogRoute = AdminCmsBlogRouteImport.update({
  id: '/admin_/cms_/blog',
  path: '/admin/cms/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsBookingRoute = AdminCmsBookingRouteImport.update({
  id: '/admin_/cms_/booking',
  path: '/admin/cms/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsContactRoute = AdminCmsContactRouteImport.update({
  id: '/admin_/cms_/contact',
  path: '/admin/cms/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsDestinationsRoute = AdminCmsDestinationsRouteImport.update({
  id: '/admin_/cms_/destinations',
  path: '/admin/cms/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsEmailTemplatesRoute = AdminCmsEmailTemplatesRouteImport.update({
  id: '/admin_/cms_/email-templates',
  path: '/admin/cms/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsExperiencesRoute = AdminCmsExperiencesRouteImport.update({
  id: '/admin_/cms_/experiences',
  path: '/admin/cms/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsFooterRoute = AdminCmsFooterRouteImport.update({
  id: '/admin_/cms_/footer',
  path: '/admin/cms/footer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsFormsRoute = AdminCmsFormsRouteImport.update({
  id: '/admin_/cms_/forms',
  path: '/admin/cms/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsGalleryRoute = AdminCmsGalleryRouteImport.update({
  id: '/admin_/cms_/gallery',
  path: '/admin/cms/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsGeneralRoute = AdminCmsGeneralRouteImport.update({
  id: '/admin_/cms_/general',
  path: '/admin/cms/general',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsHomeRoute = AdminCmsHomeRouteImport.update({
  id: '/admin_/cms_/home',
  path: '/admin/cms/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsMediaRoute = AdminCmsMediaRouteImport.update({
  id: '/admin_/cms_/media',
  path: '/admin/cms/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsNavigationRoute = AdminCmsNavigationRouteImport.update({
  id: '/admin_/cms_/navigation',
  path: '/admin/cms/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsOtherSettingsRoute = AdminCmsOtherSettingsRouteImport.update({
  id: '/admin_/cms_/other-settings',
  path: '/admin/cms/other-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsPackagesRoute = AdminCmsPackagesRouteImport.update({
  id: '/admin_/cms_/packages',
  path: '/admin/cms/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsSeoRoute = AdminCmsSeoRouteImport.update({
  id: '/admin_/cms_/seo',
  path: '/admin/cms/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsTestimonialsRoute = AdminCmsTestimonialsRouteImport.update({
  id: '/admin_/cms_/testimonials',
  path: '/admin/cms/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmBookingsRoute = AdminCrmBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminCrmRoute,
} as any)
const AdminCrmCustomersRoute = AdminCrmCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminCrmRoute,
} as any)
const AdminCrmLeadsRoute = AdminCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminCrmRoute,
} as any)
const AdminCrmPaymentsRoute = AdminCrmPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminCrmRoute,
} as any)
const AdminCmsBlogIdRoute = AdminCmsBlogIdRouteImport.update({
  id: '/admin_/cms_/blog_/$id',
  path: '/admin/cms/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsBlogListingPageRoute = AdminCmsBlogListingPageRouteImport.update({
  id: '/admin_/cms_/blog_/listing-page',
  path: '/admin/cms/blog/listing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsBlogNewRoute = AdminCmsBlogNewRouteImport.update({
  id: '/admin_/cms_/blog_/new',
  path: '/admin/cms/blog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsDestinationsIdRoute = AdminCmsDestinationsIdRouteImport.update({
  id: '/admin_/cms_/destinations_/$id',
  path: '/admin/cms/destinations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsDestinationsListingPageRoute =
  AdminCmsDestinationsListingPageRouteImport.update({
    id: '/admin_/cms_/destinations_/listing-page',
    path: '/admin/cms/destinations/listing-page',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCmsDestinationsNewRoute = AdminCmsDestinationsNewRouteImport.update({
  id: '/admin_/cms_/destinations_/new',
  path: '/admin/cms/destinations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsEmailTemplatesKeyRoute =
  AdminCmsEmailTemplatesKeyRouteImport.update({
    id: '/admin_/cms_/email-templates_/$key',
    path: '/admin/cms/email-templates/$key',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCmsExperiencesIdRoute = AdminCmsExperiencesIdRouteImport.update({
  id: '/admin_/cms_/experiences_/$id',
  path: '/admin/cms/experiences/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsExperiencesListingPageRoute =
  AdminCmsExperiencesListingPageRouteImport.update({
    id: '/admin_/cms_/experiences_/listing-page',
    path: '/admin/cms/experiences/listing-page',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCmsExperiencesNewRoute = AdminCmsExperiencesNewRouteImport.update({
  id: '/admin_/cms_/experiences_/new',
  path: '/admin/cms/experiences/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsMediaIdRoute = AdminCmsMediaIdRouteImport.update({
  id: '/admin_/cms_/media_/$id',
  path: '/admin/cms/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsNavigationKeyRoute = AdminCmsNavigationKeyRouteImport.update({
  id: '/admin_/cms_/navigation_/$key',
  path: '/admin/cms/navigation/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsPackagesIdRoute = AdminCmsPackagesIdRouteImport.update({
  id: '/admin_/cms_/packages_/$id',
  path: '/admin/cms/packages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsPackagesListingPageRoute =
  AdminCmsPackagesListingPageRouteImport.update({
    id: '/admin_/cms_/packages_/listing-page',
    path: '/admin/cms/packages/listing-page',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCmsPackagesNewRoute = AdminCmsPackagesNewRouteImport.update({
  id: '/admin_/cms_/packages_/new',
  path: '/admin/cms/packages/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsTestimonialsIdRoute = AdminCmsTestimonialsIdRouteImport.update({
  id: '/admin_/cms_/testimonials_/$id',
  path: '/admin/cms/testimonials/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsTestimonialsNewRoute = AdminCmsTestimonialsNewRouteImport.update({
  id: '/admin_/cms_/testimonials_/new',
  path: '/admin/cms/testimonials/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCrmBookingsReferenceRoute =
  AdminCrmBookingsReferenceRouteImport.update({
    id: '/bookings_/$reference',
    path: '/bookings/$reference',
    getParentRoute: () => AdminCrmRoute,
  } as any)
const AdminCrmCustomersIdRoute = AdminCrmCustomersIdRouteImport.update({
  id: '/customers_/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminCrmRoute,
} as any)
const AdminCrmBookingsCancelledReferenceRoute =
  AdminCrmBookingsCancelledReferenceRouteImport.update({
    id: '/bookings_/cancelled/$reference',
    path: '/bookings/cancelled/$reference',
    getParentRoute: () => AdminCrmRoute,
  } as any)
const AdminCrmBookingsConfirmedReferenceRoute =
  AdminCrmBookingsConfirmedReferenceRouteImport.update({
    id: '/bookings_/confirmed/$reference',
    path: '/bookings/confirmed/$reference',
    getParentRoute: () => AdminCrmRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/payment': typeof BookingPaymentRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/account/bookings/$reference': typeof AccountBookingsReferenceRoute
  '/admin/cms/about': typeof AdminCmsAboutRoute
  '/admin/cms/authentication': typeof AdminCmsAuthenticationRoute
  '/admin/cms/blog': typeof AdminCmsBlogRoute
  '/admin/cms/booking': typeof AdminCmsBookingRoute
  '/admin/cms/contact': typeof AdminCmsContactRoute
  '/admin/cms/destinations': typeof AdminCmsDestinationsRoute
  '/admin/cms/email-templates': typeof AdminCmsEmailTemplatesRoute
  '/admin/cms/experiences': typeof AdminCmsExperiencesRoute
  '/admin/cms/footer': typeof AdminCmsFooterRoute
  '/admin/cms/forms': typeof AdminCmsFormsRoute
  '/admin/cms/gallery': typeof AdminCmsGalleryRoute
  '/admin/cms/general': typeof AdminCmsGeneralRoute
  '/admin/cms/home': typeof AdminCmsHomeRoute
  '/admin/cms/media': typeof AdminCmsMediaRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/other-settings': typeof AdminCmsOtherSettingsRoute
  '/admin/cms/packages': typeof AdminCmsPackagesRoute
  '/admin/cms/seo': typeof AdminCmsSeoRoute
  '/admin/cms/testimonials': typeof AdminCmsTestimonialsRoute
  '/admin/crm/bookings': typeof AdminCrmBookingsRoute
  '/admin/crm/customers': typeof AdminCrmCustomersRoute
  '/admin/crm/leads': typeof AdminCrmLeadsRoute
  '/admin/crm/payments': typeof AdminCrmPaymentsRoute
  '/admin/cms/blog/$id': typeof AdminCmsBlogIdRoute
  '/admin/cms/blog/listing-page': typeof AdminCmsBlogListingPageRoute
  '/admin/cms/blog/new': typeof AdminCmsBlogNewRoute
  '/admin/cms/destinations/$id': typeof AdminCmsDestinationsIdRoute
  '/admin/cms/destinations/listing-page': typeof AdminCmsDestinationsListingPageRoute
  '/admin/cms/destinations/new': typeof AdminCmsDestinationsNewRoute
  '/admin/cms/email-templates/$key': typeof AdminCmsEmailTemplatesKeyRoute
  '/admin/cms/experiences/$id': typeof AdminCmsExperiencesIdRoute
  '/admin/cms/experiences/listing-page': typeof AdminCmsExperiencesListingPageRoute
  '/admin/cms/experiences/new': typeof AdminCmsExperiencesNewRoute
  '/admin/cms/media/$id': typeof AdminCmsMediaIdRoute
  '/admin/cms/navigation/$key': typeof AdminCmsNavigationKeyRoute
  '/admin/cms/packages/$id': typeof AdminCmsPackagesIdRoute
  '/admin/cms/packages/listing-page': typeof AdminCmsPackagesListingPageRoute
  '/admin/cms/packages/new': typeof AdminCmsPackagesNewRoute
  '/admin/cms/testimonials/$id': typeof AdminCmsTestimonialsIdRoute
  '/admin/cms/testimonials/new': typeof AdminCmsTestimonialsNewRoute
  '/admin/crm/bookings/$reference': typeof AdminCrmBookingsReferenceRoute
  '/admin/crm/customers/$id': typeof AdminCrmCustomersIdRoute
  '/admin/crm/bookings/cancelled/$reference': typeof AdminCrmBookingsCancelledReferenceRoute
  '/admin/crm/bookings/confirmed/$reference': typeof AdminCrmBookingsConfirmedReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/payment': typeof BookingPaymentRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/account/bookings/$reference': typeof AccountBookingsReferenceRoute
  '/admin/cms/about': typeof AdminCmsAboutRoute
  '/admin/cms/authentication': typeof AdminCmsAuthenticationRoute
  '/admin/cms/blog': typeof AdminCmsBlogRoute
  '/admin/cms/booking': typeof AdminCmsBookingRoute
  '/admin/cms/contact': typeof AdminCmsContactRoute
  '/admin/cms/destinations': typeof AdminCmsDestinationsRoute
  '/admin/cms/email-templates': typeof AdminCmsEmailTemplatesRoute
  '/admin/cms/experiences': typeof AdminCmsExperiencesRoute
  '/admin/cms/footer': typeof AdminCmsFooterRoute
  '/admin/cms/forms': typeof AdminCmsFormsRoute
  '/admin/cms/gallery': typeof AdminCmsGalleryRoute
  '/admin/cms/general': typeof AdminCmsGeneralRoute
  '/admin/cms/home': typeof AdminCmsHomeRoute
  '/admin/cms/media': typeof AdminCmsMediaRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/other-settings': typeof AdminCmsOtherSettingsRoute
  '/admin/cms/packages': typeof AdminCmsPackagesRoute
  '/admin/cms/seo': typeof AdminCmsSeoRoute
  '/admin/cms/testimonials': typeof AdminCmsTestimonialsRoute
  '/admin/crm/bookings': typeof AdminCrmBookingsRoute
  '/admin/crm/customers': typeof AdminCrmCustomersRoute
  '/admin/crm/leads': typeof AdminCrmLeadsRoute
  '/admin/crm/payments': typeof AdminCrmPaymentsRoute
  '/admin/cms/blog/$id': typeof AdminCmsBlogIdRoute
  '/admin/cms/blog/listing-page': typeof AdminCmsBlogListingPageRoute
  '/admin/cms/blog/new': typeof AdminCmsBlogNewRoute
  '/admin/cms/destinations/$id': typeof AdminCmsDestinationsIdRoute
  '/admin/cms/destinations/listing-page': typeof AdminCmsDestinationsListingPageRoute
  '/admin/cms/destinations/new': typeof AdminCmsDestinationsNewRoute
  '/admin/cms/email-templates/$key': typeof AdminCmsEmailTemplatesKeyRoute
  '/admin/cms/experiences/$id': typeof AdminCmsExperiencesIdRoute
  '/admin/cms/experiences/listing-page': typeof AdminCmsExperiencesListingPageRoute
  '/admin/cms/experiences/new': typeof AdminCmsExperiencesNewRoute
  '/admin/cms/media/$id': typeof AdminCmsMediaIdRoute
  '/admin/cms/navigation/$key': typeof AdminCmsNavigationKeyRoute
  '/admin/cms/packages/$id': typeof AdminCmsPackagesIdRoute
  '/admin/cms/packages/listing-page': typeof AdminCmsPackagesListingPageRoute
  '/admin/cms/packages/new': typeof AdminCmsPackagesNewRoute
  '/admin/cms/testimonials/$id': typeof AdminCmsTestimonialsIdRoute
  '/admin/cms/testimonials/new': typeof AdminCmsTestimonialsNewRoute
  '/admin/crm/bookings/$reference': typeof AdminCrmBookingsReferenceRoute
  '/admin/crm/customers/$id': typeof AdminCrmCustomersIdRoute
  '/admin/crm/bookings/cancelled/$reference': typeof AdminCrmBookingsCancelledReferenceRoute
  '/admin/crm/bookings/confirmed/$reference': typeof AdminCrmBookingsConfirmedReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/registration': typeof RegistrationRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/whatsapp': typeof WhatsappRoute
  '/admin_/cms': typeof AdminCmsRoute
  '/admin_/crm': typeof AdminCrmRouteWithChildren
  '/admin_/dashboard': typeof AdminDashboardRoute
  '/admin_/forgot-password': typeof AdminForgotPasswordRoute
  '/admin_/reports': typeof AdminReportsRoute
  '/admin_/reset-password': typeof AdminResetPasswordRoute
  '/admin_/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/booking/payment': typeof BookingPaymentRoute
  '/booking/success': typeof BookingSuccessRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/experiences/$slug': typeof ExperiencesSlugRoute
  '/media/$': typeof MediaSplatRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/account_/bookings/$reference': typeof AccountBookingsReferenceRoute
  '/admin_/cms_/about': typeof AdminCmsAboutRoute
  '/admin_/cms_/authentication': typeof AdminCmsAuthenticationRoute
  '/admin_/cms_/blog': typeof AdminCmsBlogRoute
  '/admin_/cms_/booking': typeof AdminCmsBookingRoute
  '/admin_/cms_/contact': typeof AdminCmsContactRoute
  '/admin_/cms_/destinations': typeof AdminCmsDestinationsRoute
  '/admin_/cms_/email-templates': typeof AdminCmsEmailTemplatesRoute
  '/admin_/cms_/experiences': typeof AdminCmsExperiencesRoute
  '/admin_/cms_/footer': typeof AdminCmsFooterRoute
  '/admin_/cms_/forms': typeof AdminCmsFormsRoute
  '/admin_/cms_/gallery': typeof AdminCmsGalleryRoute
  '/admin_/cms_/general': typeof AdminCmsGeneralRoute
  '/admin_/cms_/home': typeof AdminCmsHomeRoute
  '/admin_/cms_/media': typeof AdminCmsMediaRoute
  '/admin_/cms_/navigation': typeof AdminCmsNavigationRoute
  '/admin_/cms_/other-settings': typeof AdminCmsOtherSettingsRoute
  '/admin_/cms_/packages': typeof AdminCmsPackagesRoute
  '/admin_/cms_/seo': typeof AdminCmsSeoRoute
  '/admin_/cms_/testimonials': typeof AdminCmsTestimonialsRoute
  '/admin_/crm/bookings': typeof AdminCrmBookingsRoute
  '/admin_/crm/customers': typeof AdminCrmCustomersRoute
  '/admin_/crm/leads': typeof AdminCrmLeadsRoute
  '/admin_/crm/payments': typeof AdminCrmPaymentsRoute
  '/admin_/cms_/blog_/$id': typeof AdminCmsBlogIdRoute
  '/admin_/cms_/blog_/listing-page': typeof AdminCmsBlogListingPageRoute
  '/admin_/cms_/blog_/new': typeof AdminCmsBlogNewRoute
  '/admin_/cms_/destinations_/$id': typeof AdminCmsDestinationsIdRoute
  '/admin_/cms_/destinations_/listing-page': typeof AdminCmsDestinationsListingPageRoute
  '/admin_/cms_/destinations_/new': typeof AdminCmsDestinationsNewRoute
  '/admin_/cms_/email-templates_/$key': typeof AdminCmsEmailTemplatesKeyRoute
  '/admin_/cms_/experiences_/$id': typeof AdminCmsExperiencesIdRoute
  '/admin_/cms_/experiences_/listing-page': typeof AdminCmsExperiencesListingPageRoute
  '/admin_/cms_/experiences_/new': typeof AdminCmsExperiencesNewRoute
  '/admin_/cms_/media_/$id': typeof AdminCmsMediaIdRoute
  '/admin_/cms_/navigation_/$key': typeof AdminCmsNavigationKeyRoute
  '/admin_/cms_/packages_/$id': typeof AdminCmsPackagesIdRoute
  '/admin_/cms_/packages_/listing-page': typeof AdminCmsPackagesListingPageRoute
  '/admin_/cms_/packages_/new': typeof AdminCmsPackagesNewRoute
  '/admin_/cms_/testimonials_/$id': typeof AdminCmsTestimonialsIdRoute
  '/admin_/cms_/testimonials_/new': typeof AdminCmsTestimonialsNewRoute
  '/admin_/crm/bookings_/$reference': typeof AdminCrmBookingsReferenceRoute
  '/admin_/crm/customers_/$id': typeof AdminCrmCustomersIdRoute
  '/admin_/crm/bookings_/cancelled/$reference': typeof AdminCrmBookingsCancelledReferenceRoute
  '/admin_/crm/bookings_/confirmed/$reference': typeof AdminCrmBookingsConfirmedReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/compare'
    | '/contact'
    | '/experiences'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/registration'
    | '/reset-password'
    | '/search'
    | '/unsubscribe'
    | '/verify-email'
    | '/whatsapp'
    | '/admin/cms'
    | '/admin/crm'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/blog/$slug'
    | '/book/$slug'
    | '/booking/payment'
    | '/booking/success'
    | '/destinations/$slug'
    | '/experiences/$slug'
    | '/media/$'
    | '/packages/$slug'
    | '/blog/'
    | '/destinations/'
    | '/packages/'
    | '/account/bookings/$reference'
    | '/admin/cms/about'
    | '/admin/cms/authentication'
    | '/admin/cms/blog'
    | '/admin/cms/booking'
    | '/admin/cms/contact'
    | '/admin/cms/destinations'
    | '/admin/cms/email-templates'
    | '/admin/cms/experiences'
    | '/admin/cms/footer'
    | '/admin/cms/forms'
    | '/admin/cms/gallery'
    | '/admin/cms/general'
    | '/admin/cms/home'
    | '/admin/cms/media'
    | '/admin/cms/navigation'
    | '/admin/cms/other-settings'
    | '/admin/cms/packages'
    | '/admin/cms/seo'
    | '/admin/cms/testimonials'
    | '/admin/crm/bookings'
    | '/admin/crm/customers'
    | '/admin/crm/leads'
    | '/admin/crm/payments'
    | '/admin/cms/blog/$id'
    | '/admin/cms/blog/listing-page'
    | '/admin/cms/blog/new'
    | '/admin/cms/destinations/$id'
    | '/admin/cms/destinations/listing-page'
    | '/admin/cms/destinations/new'
    | '/admin/cms/email-templates/$key'
    | '/admin/cms/experiences/$id'
    | '/admin/cms/experiences/listing-page'
    | '/admin/cms/experiences/new'
    | '/admin/cms/media/$id'
    | '/admin/cms/navigation/$key'
    | '/admin/cms/packages/$id'
    | '/admin/cms/packages/listing-page'
    | '/admin/cms/packages/new'
    | '/admin/cms/testimonials/$id'
    | '/admin/cms/testimonials/new'
    | '/admin/crm/bookings/$reference'
    | '/admin/crm/customers/$id'
    | '/admin/crm/bookings/cancelled/$reference'
    | '/admin/crm/bookings/confirmed/$reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/compare'
    | '/contact'
    | '/experiences'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/registration'
    | '/reset-password'
    | '/search'
    | '/unsubscribe'
    | '/verify-email'
    | '/whatsapp'
    | '/admin/cms'
    | '/admin/crm'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/reports'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/blog/$slug'
    | '/book/$slug'
    | '/booking/payment'
    | '/booking/success'
    | '/destinations/$slug'
    | '/experiences/$slug'
    | '/media/$'
    | '/packages/$slug'
    | '/blog'
    | '/destinations'
    | '/packages'
    | '/account/bookings/$reference'
    | '/admin/cms/about'
    | '/admin/cms/authentication'
    | '/admin/cms/blog'
    | '/admin/cms/booking'
    | '/admin/cms/contact'
    | '/admin/cms/destinations'
    | '/admin/cms/email-templates'
    | '/admin/cms/experiences'
    | '/admin/cms/footer'
    | '/admin/cms/forms'
    | '/admin/cms/gallery'
    | '/admin/cms/general'
    | '/admin/cms/home'
    | '/admin/cms/media'
    | '/admin/cms/navigation'
    | '/admin/cms/other-settings'
    | '/admin/cms/packages'
    | '/admin/cms/seo'
    | '/admin/cms/testimonials'
    | '/admin/crm/bookings'
    | '/admin/crm/customers'
    | '/admin/crm/leads'
    | '/admin/crm/payments'
    | '/admin/cms/blog/$id'
    | '/admin/cms/blog/listing-page'
    | '/admin/cms/blog/new'
    | '/admin/cms/destinations/$id'
    | '/admin/cms/destinations/listing-page'
    | '/admin/cms/destinations/new'
    | '/admin/cms/email-templates/$key'
    | '/admin/cms/experiences/$id'
    | '/admin/cms/experiences/listing-page'
    | '/admin/cms/experiences/new'
    | '/admin/cms/media/$id'
    | '/admin/cms/navigation/$key'
    | '/admin/cms/packages/$id'
    | '/admin/cms/packages/listing-page'
    | '/admin/cms/packages/new'
    | '/admin/cms/testimonials/$id'
    | '/admin/cms/testimonials/new'
    | '/admin/crm/bookings/$reference'
    | '/admin/crm/customers/$id'
    | '/admin/crm/bookings/cancelled/$reference'
    | '/admin/crm/bookings/confirmed/$reference'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/compare'
    | '/contact'
    | '/experiences'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/login'
    | '/registration'
    | '/reset-password'
    | '/search'
    | '/unsubscribe'
    | '/verify-email'
    | '/whatsapp'
    | '/admin_/cms'
    | '/admin_/crm'
    | '/admin_/dashboard'
    | '/admin_/forgot-password'
    | '/admin_/reports'
    | '/admin_/reset-password'
    | '/admin_/settings'
    | '/blog/$slug'
    | '/book/$slug'
    | '/booking/payment'
    | '/booking/success'
    | '/destinations/$slug'
    | '/experiences/$slug'
    | '/media/$'
    | '/packages/$slug'
    | '/blog/'
    | '/destinations/'
    | '/packages/'
    | '/account_/bookings/$reference'
    | '/admin_/cms_/about'
    | '/admin_/cms_/authentication'
    | '/admin_/cms_/blog'
    | '/admin_/cms_/booking'
    | '/admin_/cms_/contact'
    | '/admin_/cms_/destinations'
    | '/admin_/cms_/email-templates'
    | '/admin_/cms_/experiences'
    | '/admin_/cms_/footer'
    | '/admin_/cms_/forms'
    | '/admin_/cms_/gallery'
    | '/admin_/cms_/general'
    | '/admin_/cms_/home'
    | '/admin_/cms_/media'
    | '/admin_/cms_/navigation'
    | '/admin_/cms_/other-settings'
    | '/admin_/cms_/packages'
    | '/admin_/cms_/seo'
    | '/admin_/cms_/testimonials'
    | '/admin_/crm/bookings'
    | '/admin_/crm/customers'
    | '/admin_/crm/leads'
    | '/admin_/crm/payments'
    | '/admin_/cms_/blog_/$id'
    | '/admin_/cms_/blog_/listing-page'
    | '/admin_/cms_/blog_/new'
    | '/admin_/cms_/destinations_/$id'
    | '/admin_/cms_/destinations_/listing-page'
    | '/admin_/cms_/destinations_/new'
    | '/admin_/cms_/email-templates_/$key'
    | '/admin_/cms_/experiences_/$id'
    | '/admin_/cms_/experiences_/listing-page'
    | '/admin_/cms_/experiences_/new'
    | '/admin_/cms_/media_/$id'
    | '/admin_/cms_/navigation_/$key'
    | '/admin_/cms_/packages_/$id'
    | '/admin_/cms_/packages_/listing-page'
    | '/admin_/cms_/packages_/new'
    | '/admin_/cms_/testimonials_/$id'
    | '/admin_/cms_/testimonials_/new'
    | '/admin_/crm/bookings_/$reference'
    | '/admin_/crm/customers_/$id'
    | '/admin_/crm/bookings_/cancelled/$reference'
    | '/admin_/crm/bookings_/confirmed/$reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  ExperiencesRoute: typeof ExperiencesRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  RegistrationRoute: typeof RegistrationRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WhatsappRoute: typeof WhatsappRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCrmRoute: typeof AdminCrmRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BookSlugRoute: typeof BookSlugRoute
  BookingPaymentRoute: typeof BookingPaymentRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  MediaSplatRoute: typeof MediaSplatRoute
  PackagesSlugRoute: typeof PackagesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  AccountBookingsReferenceRoute: typeof AccountBookingsReferenceRoute
  AdminCmsAboutRoute: typeof AdminCmsAboutRoute
  AdminCmsAuthenticationRoute: typeof AdminCmsAuthenticationRoute
  AdminCmsBlogRoute: typeof AdminCmsBlogRoute
  AdminCmsBookingRoute: typeof AdminCmsBookingRoute
  AdminCmsContactRoute: typeof AdminCmsContactRoute
  AdminCmsDestinationsRoute: typeof AdminCmsDestinationsRoute
  AdminCmsEmailTemplatesRoute: typeof AdminCmsEmailTemplatesRoute
  AdminCmsExperiencesRoute: typeof AdminCmsExperiencesRoute
  AdminCmsFooterRoute: typeof AdminCmsFooterRoute
  AdminCmsFormsRoute: typeof AdminCmsFormsRoute
  AdminCmsGalleryRoute: typeof AdminCmsGalleryRoute
  AdminCmsGeneralRoute: typeof AdminCmsGeneralRoute
  AdminCmsHomeRoute: typeof AdminCmsHomeRoute
  AdminCmsMediaRoute: typeof AdminCmsMediaRoute
  AdminCmsNavigationRoute: typeof AdminCmsNavigationRoute
  AdminCmsOtherSettingsRoute: typeof AdminCmsOtherSettingsRoute
  AdminCmsPackagesRoute: typeof AdminCmsPackagesRoute
  AdminCmsSeoRoute: typeof AdminCmsSeoRoute
  AdminCmsTestimonialsRoute: typeof AdminCmsTestimonialsRoute
  AdminCmsBlogIdRoute: typeof AdminCmsBlogIdRoute
  AdminCmsBlogListingPageRoute: typeof AdminCmsBlogListingPageRoute
  AdminCmsBlogNewRoute: typeof AdminCmsBlogNewRoute
  AdminCmsDestinationsIdRoute: typeof AdminCmsDestinationsIdRoute
  AdminCmsDestinationsListingPageRoute: typeof AdminCmsDestinationsListingPageRoute
  AdminCmsDestinationsNewRoute: typeof AdminCmsDestinationsNewRoute
  AdminCmsEmailTemplatesKeyRoute: typeof AdminCmsEmailTemplatesKeyRoute
  AdminCmsExperiencesIdRoute: typeof AdminCmsExperiencesIdRoute
  AdminCmsExperiencesListingPageRoute: typeof AdminCmsExperiencesListingPageRoute
  AdminCmsExperiencesNewRoute: typeof AdminCmsExperiencesNewRoute
  AdminCmsMediaIdRoute: typeof AdminCmsMediaIdRoute
  AdminCmsNavigationKeyRoute: typeof AdminCmsNavigationKeyRoute
  AdminCmsPackagesIdRoute: typeof AdminCmsPackagesIdRoute
  AdminCmsPackagesListingPageRoute: typeof AdminCmsPackagesListingPageRoute
  AdminCmsPackagesNewRoute: typeof AdminCmsPackagesNewRoute
  AdminCmsTestimonialsIdRoute: typeof AdminCmsTestimonialsIdRoute
  AdminCmsTestimonialsNewRoute: typeof AdminCmsTestimonialsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms': {
      id: '/admin_/cms'
      path: '/admin/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/crm': {
      id: '/admin_/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/dashboard': {
      id: '/admin_/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/forgot-password': {
      id: '/admin_/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reports': {
      id: '/admin_/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/reset-password': {
      id: '/admin_/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/settings': {
      id: '/admin_/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/payment': {
      id: '/booking/payment'
      path: '/booking/payment'
      fullPath: '/booking/payment'
      preLoaderRoute: typeof BookingPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$slug': {
      id: '/experiences/$slug'
      path: '/$slug'
      fullPath: '/experiences/$slug'
      preLoaderRoute: typeof ExperiencesSlugRouteImport
      parentRoute: typeof ExperiencesRoute
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/packages/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/bookings/$reference': {
      id: '/account_/bookings/$reference'
      path: '/account/bookings/$reference'
      fullPath: '/account/bookings/$reference'
      preLoaderRoute: typeof AccountBookingsReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/about': {
      id: '/admin_/cms_/about'
      path: '/admin/cms/about'
      fullPath: '/admin/cms/about'
      preLoaderRoute: typeof AdminCmsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/authentication': {
      id: '/admin_/cms_/authentication'
      path: '/admin/cms/authentication'
      fullPath: '/admin/cms/authentication'
      preLoaderRoute: typeof AdminCmsAuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/blog': {
      id: '/admin_/cms_/blog'
      path: '/admin/cms/blog'
      fullPath: '/admin/cms/blog'
      preLoaderRoute: typeof AdminCmsBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/booking': {
      id: '/admin_/cms_/booking'
      path: '/admin/cms/booking'
      fullPath: '/admin/cms/booking'
      preLoaderRoute: typeof AdminCmsBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/contact': {
      id: '/admin_/cms_/contact'
      path: '/admin/cms/contact'
      fullPath: '/admin/cms/contact'
      preLoaderRoute: typeof AdminCmsContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/destinations': {
      id: '/admin_/cms_/destinations'
      path: '/admin/cms/destinations'
      fullPath: '/admin/cms/destinations'
      preLoaderRoute: typeof AdminCmsDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/email-templates': {
      id: '/admin_/cms_/email-templates'
      path: '/admin/cms/email-templates'
      fullPath: '/admin/cms/email-templates'
      preLoaderRoute: typeof AdminCmsEmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/experiences': {
      id: '/admin_/cms_/experiences'
      path: '/admin/cms/experiences'
      fullPath: '/admin/cms/experiences'
      preLoaderRoute: typeof AdminCmsExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/footer': {
      id: '/admin_/cms_/footer'
      path: '/admin/cms/footer'
      fullPath: '/admin/cms/footer'
      preLoaderRoute: typeof AdminCmsFooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/forms': {
      id: '/admin_/cms_/forms'
      path: '/admin/cms/forms'
      fullPath: '/admin/cms/forms'
      preLoaderRoute: typeof AdminCmsFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/gallery': {
      id: '/admin_/cms_/gallery'
      path: '/admin/cms/gallery'
      fullPath: '/admin/cms/gallery'
      preLoaderRoute: typeof AdminCmsGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/general': {
      id: '/admin_/cms_/general'
      path: '/admin/cms/general'
      fullPath: '/admin/cms/general'
      preLoaderRoute: typeof AdminCmsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/home': {
      id: '/admin_/cms_/home'
      path: '/admin/cms/home'
      fullPath: '/admin/cms/home'
      preLoaderRoute: typeof AdminCmsHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/media': {
      id: '/admin_/cms_/media'
      path: '/admin/cms/media'
      fullPath: '/admin/cms/media'
      preLoaderRoute: typeof AdminCmsMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/navigation': {
      id: '/admin_/cms_/navigation'
      path: '/admin/cms/navigation'
      fullPath: '/admin/cms/navigation'
      preLoaderRoute: typeof AdminCmsNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/other-settings': {
      id: '/admin_/cms_/other-settings'
      path: '/admin/cms/other-settings'
      fullPath: '/admin/cms/other-settings'
      preLoaderRoute: typeof AdminCmsOtherSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/packages': {
      id: '/admin_/cms_/packages'
      path: '/admin/cms/packages'
      fullPath: '/admin/cms/packages'
      preLoaderRoute: typeof AdminCmsPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/seo': {
      id: '/admin_/cms_/seo'
      path: '/admin/cms/seo'
      fullPath: '/admin/cms/seo'
      preLoaderRoute: typeof AdminCmsSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/testimonials': {
      id: '/admin_/cms_/testimonials'
      path: '/admin/cms/testimonials'
      fullPath: '/admin/cms/testimonials'
      preLoaderRoute: typeof AdminCmsTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/crm/bookings': {
      id: '/admin_/crm/bookings'
      path: '/bookings'
      fullPath: '/admin/crm/bookings'
      preLoaderRoute: typeof AdminCrmBookingsRouteImport
      parentRoute: typeof AdminCrmRoute
    }
    '/admin_/crm/customers': {
      id: '/admin_/crm/customers'
      path: '/customers'
      fullPath: '/admin/crm/customers'
      preLoaderRoute: typeof AdminCrmCustomersRouteImport
      parentRoute: typeof AdminCrmRoute
    }
    '/admin_/crm/leads': {
      id: '/admin_/crm/leads'
      path: '/leads'
      fullPath: '/admin/crm/leads'
      preLoaderRoute: typeof AdminCrmLeadsRouteImport
      parentRoute: typeof AdminCrmRoute
    }
    '/admin_/crm/payments': {
      id: '/admin_/crm/payments'
      path: '/payments'
      fullPath: '/admin/crm/payments'
      preLoaderRoute: typeof AdminCrmPaymentsRouteImport
      parentRoute: typeof AdminCrmRoute
    }
    '/admin_/cms_/blog_/$id': {
      id: '/admin_/cms_/blog_/$id'
      path: '/admin/cms/blog/$id'
      fullPath: '/admin/cms/blog/$id'
      preLoaderRoute: typeof AdminCmsBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/blog_/listing-page': {
      id: '/admin_/cms_/blog_/listing-page'
      path: '/admin/cms/blog/listing-page'
      fullPath: '/admin/cms/blog/listing-page'
      preLoaderRoute: typeof AdminCmsBlogListingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/blog_/new': {
      id: '/admin_/cms_/blog_/new'
      path: '/admin/cms/blog/new'
      fullPath: '/admin/cms/blog/new'
      preLoaderRoute: typeof AdminCmsBlogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/destinations_/$id': {
      id: '/admin_/cms_/destinations_/$id'
      path: '/admin/cms/destinations/$id'
      fullPath: '/admin/cms/destinations/$id'
      preLoaderRoute: typeof AdminCmsDestinationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/destinations_/listing-page': {
      id: '/admin_/cms_/destinations_/listing-page'
      path: '/admin/cms/destinations/listing-page'
      fullPath: '/admin/cms/destinations/listing-page'
      preLoaderRoute: typeof AdminCmsDestinationsListingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/destinations_/new': {
      id: '/admin_/cms_/destinations_/new'
      path: '/admin/cms/destinations/new'
      fullPath: '/admin/cms/destinations/new'
      preLoaderRoute: typeof AdminCmsDestinationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/email-templates_/$key': {
      id: '/admin_/cms_/email-templates_/$key'
      path: '/admin/cms/email-templates/$key'
      fullPath: '/admin/cms/email-templates/$key'
      preLoaderRoute: typeof AdminCmsEmailTemplatesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/experiences_/$id': {
      id: '/admin_/cms_/experiences_/$id'
      path: '/admin/cms/experiences/$id'
      fullPath: '/admin/cms/experiences/$id'
      preLoaderRoute: typeof AdminCmsExperiencesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/experiences_/listing-page': {
      id: '/admin_/cms_/experiences_/listing-page'
      path: '/admin/cms/experiences/listing-page'
      fullPath: '/admin/cms/experiences/listing-page'
      preLoaderRoute: typeof AdminCmsExperiencesListingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/experiences_/new': {
      id: '/admin_/cms_/experiences_/new'
      path: '/admin/cms/experiences/new'
      fullPath: '/admin/cms/experiences/new'
      preLoaderRoute: typeof AdminCmsExperiencesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/media_/$id': {
      id: '/admin_/cms_/media_/$id'
      path: '/admin/cms/media/$id'
      fullPath: '/admin/cms/media/$id'
      preLoaderRoute: typeof AdminCmsMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/navigation_/$key': {
      id: '/admin_/cms_/navigation_/$key'
      path: '/admin/cms/navigation/$key'
      fullPath: '/admin/cms/navigation/$key'
      preLoaderRoute: typeof AdminCmsNavigationKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/packages_/$id': {
      id: '/admin_/cms_/packages_/$id'
      path: '/admin/cms/packages/$id'
      fullPath: '/admin/cms/packages/$id'
      preLoaderRoute: typeof AdminCmsPackagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/packages_/listing-page': {
      id: '/admin_/cms_/packages_/listing-page'
      path: '/admin/cms/packages/listing-page'
      fullPath: '/admin/cms/packages/listing-page'
      preLoaderRoute: typeof AdminCmsPackagesListingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/packages_/new': {
      id: '/admin_/cms_/packages_/new'
      path: '/admin/cms/packages/new'
      fullPath: '/admin/cms/packages/new'
      preLoaderRoute: typeof AdminCmsPackagesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/testimonials_/$id': {
      id: '/admin_/cms_/testimonials_/$id'
      path: '/admin/cms/testimonials/$id'
      fullPath: '/admin/cms/testimonials/$id'
      preLoaderRoute: typeof AdminCmsTestimonialsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/cms_/testimonials_/new': {
      id: '/admin_/cms_/testimonials_/new'
      path: '/admin/cms/testimonials/new'
      fullPath: '/admin/cms/testimonials/new'
      preLoaderRoute: typeof AdminCmsTestimonialsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/crm/bookings_/$reference': {
      id: '/admin_/crm/bookings_/$reference'
      path: '/bookings/$reference'
      fullPath: '/admin/crm/bookings/$reference'
      preLoaderRoute: typeof AdminCrmBookingsReferenceRouteImport
      parentRoute: typeof AdminCrmRoute
    }
    '/admin_/crm/customers_/$id': {
      id: '/admin_/crm/customers_/$id'
      path: '/customers/$id'
      fullPath: '/admin/crm/customers/$id'
      preLoaderRoute: typeof AdminCrmCustomersIdRouteImport
      parentRoute: typeof AdminCrmRoute
    }
    '/admin_/crm/bookings_/cancelled/$reference': {
      id: '/admin_/crm/bookings_/cancelled/$reference'
      path: '/bookings/cancelled/$reference'
      fullPath: '/admin/crm/bookings/cancelled/$reference'
      preLoaderRoute: typeof AdminCrmBookingsCancelledReferenceRouteImport
      parentRoute: typeof AdminCrmRoute
    }
    '/admin_/crm/bookings_/confirmed/$reference': {
      id: '/admin_/crm/bookings_/confirmed/$reference'
      path: '/bookings/confirmed/$reference'
      fullPath: '/admin/crm/bookings/confirmed/$reference'
      preLoaderRoute: typeof AdminCrmBookingsConfirmedReferenceRouteImport
      parentRoute: typeof AdminCrmRoute
    }
  }
}

interface ExperiencesRouteChildren {
  ExperiencesSlugRoute: typeof ExperiencesSlugRoute
}

const ExperiencesRouteChildren: ExperiencesRouteChildren = {
  ExperiencesSlugRoute: ExperiencesSlugRoute,
}

const ExperiencesRouteWithChildren = ExperiencesRoute._addFileChildren(
  ExperiencesRouteChildren,
)

interface AdminCrmRouteChildren {
  AdminCrmBookingsRoute: typeof AdminCrmBookingsRoute
  AdminCrmCustomersRoute: typeof AdminCrmCustomersRoute
  AdminCrmLeadsRoute: typeof AdminCrmLeadsRoute
  AdminCrmPaymentsRoute: typeof AdminCrmPaymentsRoute
  AdminCrmBookingsReferenceRoute: typeof AdminCrmBookingsReferenceRoute
  AdminCrmCustomersIdRoute: typeof AdminCrmCustomersIdRoute
  AdminCrmBookingsCancelledReferenceRoute: typeof AdminCrmBookingsCancelledReferenceRoute
  AdminCrmBookingsConfirmedReferenceRoute: typeof AdminCrmBookingsConfirmedReferenceRoute
}

const AdminCrmRouteChildren: AdminCrmRouteChildren = {
  AdminCrmBookingsRoute: AdminCrmBookingsRoute,
  AdminCrmCustomersRoute: AdminCrmCustomersRoute,
  AdminCrmLeadsRoute: AdminCrmLeadsRoute,
  AdminCrmPaymentsRoute: AdminCrmPaymentsRoute,
  AdminCrmBookingsReferenceRoute: AdminCrmBookingsReferenceRoute,
  AdminCrmCustomersIdRoute: AdminCrmCustomersIdRoute,
  AdminCrmBookingsCancelledReferenceRoute:
    AdminCrmBookingsCancelledReferenceRoute,
  AdminCrmBookingsConfirmedReferenceRoute:
    AdminCrmBookingsConfirmedReferenceRoute,
}

const AdminCrmRouteWithChildren = AdminCrmRoute._addFileChildren(
  AdminCrmRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  ExperiencesRoute: ExperiencesRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  RegistrationRoute: RegistrationRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WhatsappRoute: WhatsappRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCrmRoute: AdminCrmRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BookSlugRoute: BookSlugRoute,
  BookingPaymentRoute: BookingPaymentRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  MediaSplatRoute: MediaSplatRoute,
  PackagesSlugRoute: PackagesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  AccountBookingsReferenceRoute: AccountBookingsReferenceRoute,
  AdminCmsAboutRoute: AdminCmsAboutRoute,
  AdminCmsAuthenticationRoute: AdminCmsAuthenticationRoute,
  AdminCmsBlogRoute: AdminCmsBlogRoute,
  AdminCmsBookingRoute: AdminCmsBookingRoute,
  AdminCmsContactRoute: AdminCmsContactRoute,
  AdminCmsDestinationsRoute: AdminCmsDestinationsRoute,
  AdminCmsEmailTemplatesRoute: AdminCmsEmailTemplatesRoute,
  AdminCmsExperiencesRoute: AdminCmsExperiencesRoute,
  AdminCmsFooterRoute: AdminCmsFooterRoute,
  AdminCmsFormsRoute: AdminCmsFormsRoute,
  AdminCmsGalleryRoute: AdminCmsGalleryRoute,
  AdminCmsGeneralRoute: AdminCmsGeneralRoute,
  AdminCmsHomeRoute: AdminCmsHomeRoute,
  AdminCmsMediaRoute: AdminCmsMediaRoute,
  AdminCmsNavigationRoute: AdminCmsNavigationRoute,
  AdminCmsOtherSettingsRoute: AdminCmsOtherSettingsRoute,
  AdminCmsPackagesRoute: AdminCmsPackagesRoute,
  AdminCmsSeoRoute: AdminCmsSeoRoute,
  AdminCmsTestimonialsRoute: AdminCmsTestimonialsRoute,
  AdminCmsBlogIdRoute: AdminCmsBlogIdRoute,
  AdminCmsBlogListingPageRoute: AdminCmsBlogListingPageRoute,
  AdminCmsBlogNewRoute: AdminCmsBlogNewRoute,
  AdminCmsDestinationsIdRoute: AdminCmsDestinationsIdRoute,
  AdminCmsDestinationsListingPageRoute: AdminCmsDestinationsListingPageRoute,
  AdminCmsDestinationsNewRoute: AdminCmsDestinationsNewRoute,
  AdminCmsEmailTemplatesKeyRoute: AdminCmsEmailTemplatesKeyRoute,
  AdminCmsExperiencesIdRoute: AdminCmsExperiencesIdRoute,
  AdminCmsExperiencesListingPageRoute: AdminCmsExperiencesListingPageRoute,
  AdminCmsExperiencesNewRoute: AdminCmsExperiencesNewRoute,
  AdminCmsMediaIdRoute: AdminCmsMediaIdRoute,
  AdminCmsNavigationKeyRoute: AdminCmsNavigationKeyRoute,
  AdminCmsPackagesIdRoute: AdminCmsPackagesIdRoute,
  AdminCmsPackagesListingPageRoute: AdminCmsPackagesListingPageRoute,
  AdminCmsPackagesNewRoute: AdminCmsPackagesNewRoute,
  AdminCmsTestimonialsIdRoute: AdminCmsTestimonialsIdRoute,
  AdminCmsTestimonialsNewRoute: AdminCmsTestimonialsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
